# Generated by Django 5.0.4 on 2024-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='subtopics', to='school_management.goal'),
        ),
    ]
