# Generated by Django 5.0.4 on 2024-04-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_rename_topic_id_subtopic_topic_subtopic_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='topic',
            new_name='topic_id',
        ),
    ]
