# Generated by Django 5.0.4 on 2024-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_rename_topic_subtopic_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='keyboard_elements',
            field=models.ManyToManyField(related_name='tasks', to='school_management.keyboardelement'),
        ),
    ]
