# Generated by Django 5.0.4 on 2024-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_remove_task_formulas_alter_task_correct_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtopic_id',
            new_name='subtopic',
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answers',
            field=models.TextField(),
        ),
    ]
