# Generated by Django 5.0.4 on 2024-04-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_rename_subtopic_id_task_subtopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='keyboard_elements',
        ),
    ]
