# Generated by Django 5.0.4 on 2024-04-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_remove_task_keyboard_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='correct_answers',
        ),
    ]
