# Generated by Django 5.0.4 on 2024-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_remove_task_correct_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtopic',
            new_name='subtopic_id',
        ),
    ]
