# Generated by Django 5.0.4 on 2024-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0009_rename_subtopic_task_subtopic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='hints',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='solutions',
            field=models.CharField(max_length=255),
        ),
    ]
