# Generated by Django 5.0.4 on 2024-04-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0010_alter_task_description_alter_task_hints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='task',
            name='solutions',
        ),
    ]
