# Generated by Django 5.0.4 on 2024-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0012_task_correct_answers_task_description_task_hints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtopic_id',
            new_name='subtopic',
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='hints',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='keyboard_elements',
            field=models.ManyToManyField(related_name='tasks', to='school_management.keyboardelement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solutions',
            field=models.TextField(),
        ),
    ]
