# Generated by Django 5.0.4 on 2024-04-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0013_rename_subtopic_id_task_subtopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school_management.class')),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school_management.goal')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school_management.task')),
            ],
        ),
    ]
