# Generated by Django 5.0.4 on 2024-04-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0014_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='class_id',
        ),
    ]
