# Generated by Django 5.0.4 on 2024-04-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0015_remove_test_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='goal_id',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='test',
            name='task_id',
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tasks', to='school_management.task')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tasks', to='school_management.test')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=255)),
                ('current_test_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='school_management.testtask')),
                ('next_task_for_correct_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_transitions', to='school_management.testtask')),
                ('next_task_for_incorrect_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_transitions', to='school_management.testtask')),
            ],
        ),
    ]
