# Generated by Django 5.0.4 on 2024-04-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0016_rename_goal_id_test_goal_remove_test_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='test',
        ),
        migrations.AlterField(
            model_name='test',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.goal'),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_task_on_correct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='school_management.task')),
                ('next_task_on_incorrect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='school_management.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.task')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school_management.test')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskTransition',
        ),
        migrations.DeleteModel(
            name='TestTask',
        ),
    ]
