# Generated by Django 5.0.4 on 2024-04-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0017_remove_testtask_task_remove_testtask_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='goal',
        ),
        migrations.CreateModel(
            name='TaskInTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_task_correct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_correct_tasks', to='school_management.task')),
                ('next_task_incorrect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_incorrect_tasks', to='school_management.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tasks', to='school_management.task')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskintest_set', to='school_management.test')),
            ],
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
