# Generated by Django 5.0.4 on 2024-04-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0018_remove_test_goal_taskintest_delete_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school_management.goal'),
            preserve_default=False,
        ),
    ]
