# Generated by Django 5.0.4 on 2024-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0019_test_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correct_option',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
