# Generated by Django 5.0.4 on 2024-05-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0020_task_correct_option_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='correct_answers',
        ),
    ]
