# Generated by Django 5.0.4 on 2024-05-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0021_remove_task_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_option',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
