# Generated by Django 5.0.4 on 2024-05-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0022_alter_task_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_option',
            field=models.CharField(max_length=1),
        ),
    ]
